document.write("<header class='header'>");
document.write("<a href='../pages/index.html' class='logoName'>&#123;Iago Dev&#125</a>");
document.write("<nav><ul>");
document.write("<li class='drop'>");
document.write("<p>Atividades</p>");
document.write("<ul class='dropdown-menu'>");
document.write("<li><a href='../pages/verificaIdade.html'>Verificar Idade</a></li>");
document.write("<li><a href='../pages/verificaAluno.html'>Verificar Aluno</a></li>");
document.write("<li><a href='../pages/verificaIMC.html'>Verificar IMC</a></li>");
document.write("<li><a href='../pages/verificaAumento.html'>Verificar Aumento</a></li>");
document.write("<li><a  href='../pages/adicionarFrutas.html'>Adicionar Frutras</a></li>");
document.write("<li><a  href='../pages/cadastroContatos.html'>Cadastrar Contato</a></li>");
document.write("<li><a  href='../pages/cardFetch.html'>Card Fetch</a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li><a href='https://www.linkedin.com/in/iago-gondim/'>Contato</a></li>");
document.write("</ul></nv>");
document.write("</header>");